config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "drawings#index"

  devise_for :users

  resources :drawings do
    resources :tickets
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drawing.rb
class Drawing < ApplicationRecord
  has_many :tickets, class_name: "Ticket", foreign_key: "drawing_id", dependent: :delete_all
  has_many :winning_picks, class_name: "WinningPick", foreign_key: "drawing_id", dependent: :delete_all

  def winning_numbers
    numbers = Array.new
    self.winning_picks.each do |pick|
      numbers.push(pick.ball_number)
    end
    return numbers
  end
end

app/models/pick.rb
class Pick < ApplicationRecord
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :picks, class_name: "Pick", foreign_key: "ticket_id", dependent: :delete_all

  def ticket_numbers
    numbers = Array.new
    self.picks.each do |pick|
      numbers.push(pick.ball_number)
    end
    return numbers
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :tickets, class_name: "Ticket", foreign_key: "user_id", dependent: :delete_all
end

app/models/winning_pick.rb
class WinningPick < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @drawings = Drawing.order(id: :desc)
  end
 
  def show
    @drawing = Drawing.find(params[:id])
    @user_tickets = Ticket.where(user_id: current_user.id, drawing_id: params[:id])
    @is_winner = false

    if @drawing.drawing_on and @user_tickets
      @user_tickets.each do |ticket|
        # Compare ticket numbers array and winning numbers array
        if (ticket.ticket_numbers - @drawing.winning_numbers).length() == 0
          @is_winner = true
        end
      end
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!

  def create
    @drawing = Drawing.find(params[:drawing_id])
    if params[:ball_numbers].kind_of?(Array)
      ticket = Ticket.create(drawing_id: @drawing.id, user_id: current_user.id)
      for ball_number in params[:ball_numbers].sort
        Pick.create(ticket_id: ticket.id, ball_number: ball_number)
      end
    end
    redirect_to drawing_path(@drawing)
  end

  private
    def ticket_params
      params.permit(:ball_numbers)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drawings_helper.rb
module DrawingsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/drawings/index.html.erb
<h1>Latest Mark Six Drawings</h1>  
<table class="table table-striped">
  <thead>
    <tr>
      <th>Id</th>
      <th>Title</th>
      <th>Date</th>
      <th>Winning Numbers</th>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
  <% @drawings.each do |drawing| %>
    <tr>
      <td><%= drawing.id %></td>
      <td><%= drawing.title %></td>
      <td><%= drawing.created_at %></td>
      <td>
        <% drawing.winning_numbers.sort.each do |numbers| %>
          <%= numbers %>
        <% end %>
      </td>
      <td><%= drawing.drawing_on ? 'Finished' : 'Available' %></td>
      <% if drawing.drawing_on %>
        <td><%= link_to 'Show', drawing_path(drawing) %></td>
      <% else %>
        <td><%= link_to 'Buy', drawing_path(drawing) %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/drawings/new.html.erb
<%= form_with scope: :drawing, url: drawings_path, local: true do |form| %>
 
  <% if @drawing.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@drawing.errors.count, "error") %> prohibited
        this drawing from being saved:
      </h2>
      <ul>
        <% @drawing.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :drawing_type %><br>
    <%= form.text_field :drawing_type %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', drawings_path %>

app/views/drawings/show.html.erb
<h2>
<%= @drawing.title %>
</h2>
<p>
<% if @drawing.drawing_on%>
  <% if @is_winner %>
    <h4>Congratulation! You are the winner! </h4>
  <% else %>
    <h4>What a pity! Add oid next time! </h4>
  <% end %>
<% end %>
</p>
<hr/>
<h4>Final Winning Picks: </h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Drawing On</th>
      <th>Numbers</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @drawing.drawing_on %></td>
      <td>
        <% @drawing.winning_picks.each do |winning_pick| %>
          <%= winning_pick.ball_number %>
        <% end %>
      </td>
      <td><%= @drawing.drawing_on ? 'Finished' : 'Available' %></td>
    </tr>
  </tbody>
</table>
<hr/>
<h4>Your Ticket Records:</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Drawing</th>
      <th>Numbers</th>
      <th>Date</th>
    </tr>
  </thead>
  <tbody>
  <% if @user_tickets %>
    <% @user_tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.drawing_id %></td>
        <td>
          <% ticket.ticket_numbers.sort.each do |number| %>
            <%= number %>
          <% end %>
        </td>
        <td><%= ticket.created_at %></td>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>
<hr/>
<% if not @drawing.drawing_on %>
  <h4>Buy a ticket:</h4>
  <%= form_with(model: [ @drawing, @drawing.tickets.build ], local: true, id: "picks") do |form| %>
    <p>
      <p>Please pick 6 numbers!</p>
      <% 1.upto(10) do |i| -%>
        <label class="checkbox-inline">
          <input name="ball_numbers[]" value="<%= i %>"  type= "checkbox"/>
          <%= i -%>
        </label>
      <% end %>
    </p>
    <p>
      <%= form.submit "Buy" %>
    </p>
  <% end %>
<% end %>

<script type="text/javascript">

  function checkboxlimit(checkgroup, limit){
    var checkgroup = checkgroup
    var limit = limit
    for (var i = 0; i < checkgroup.length; i++){
      checkgroup[i].onclick = function(){
      var checkedcount = 0
      for (var i = 0; i < checkgroup.length; i++)
        checkedcount += (checkgroup[i].checked) ? 1 : 0
      if (checkedcount > limit){
        alert("You can only select a maximum of "+limit+" ball numbers")
        this.checked = false
        }
      }
    }
  }

</script>

<script type="text/javascript">
  $(document).ready(function(){
    checkboxlimit(document.forms.picks.elements['ball_numbers[]'], 6);

    $("form").submit(function(){
		if ($('input:checkbox').filter(':checked').length < 1){
        alert("Please pick 6 numbers!");
		return false;
		}
    });
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lotto</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Mark Six</a>
        </div>
        <!-- <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/ideas">Ideas</a></li>
          </ul>
        </div> -->
        <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
        </p>
      </div>
    </nav>
    <div class="container">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
    <footer>
      <div class="container">
        Paul Chen <%= Time.now.year %>
      </div>
    </footer>
  </body>
</html>